//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderedItems
    {
        public int OrderedItemsId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Tbl_Orders Tbl_Orders { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
